name: hamler
version: '0.0.1'
synopsis: The Hamler Programming Language
description: Hamler is a functional programming language inspired by Haskell and Stardard ML,
  that compiles to Core Erlang.
category: Language, Compiler
author: Feng Lee <feng@emqx.io>
maintainer: Feng Lee <feng@emqx.io>
copyright: (c) 2013-17 Phil Freeman, (c) 2014-19 Gary Burgess, (c) other contributors (see CONTRIBUTORS.md)
license: BSD3
github: hamler-lang/hamler
homepage: http://www.hamler.io/
extra-source-files:
  - README.md
  - stack.yaml
dependencies:
  - base >=4.11 && <4.13
  - base-compat >=0.6.0
  - boxes >=0.1.4 && <0.2.0
  - bytestring
  - Cabal >= 2.2 && <3.0
  - containers
  - purescript
  - directory >=1.2.3
  - CoreErlang
  - filepath
  - Glob >=0.9 && <0.10
  - monad-control >=1.0.0.0 && <1.1
  - mtl >=2.1.0 && <2.3.0
  - parsec >=3.1.10
  - pattern-arrows >=0.0.2 && <0.1
  - pretty >= 1.1
  - process >=1.2.0 && <1.7
  - protolude >=0.1.6 && <0.2.4
  - text
  - time
  - transformers >=0.3.0 && <0.6
  - transformers-base >=0.4.0 && <0.5
  - transformers-compat >=0.3.0
  - utf8-string >=1 && <2
build-tools:
  - happy ==1.19.9

library:
  source-dirs: src
  # ghc-options: -Wall -O2
  ghc-options:  -O2
  # other-modules:
  default-extensions:
    - ConstraintKinds
    - DataKinds
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - DeriveGeneric
    - DerivingStrategies
    - EmptyDataDecls
    - FlexibleContexts
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - PatternGuards
    - PatternSynonyms
    - RankNTypes
    - RecordWildCards
    - OverloadedStrings
    - ScopedTypeVariables
    - TupleSections
    - ViewPatterns

executables:
  hamler:
    main: Main.hs
    source-dirs: app
    # ghc-options: -Wall -O2
    dependencies:
      - ansi-wl-pprint
      - hamler
      - optparse-applicative >=0.13.0
    when:
    - condition: flag(release)
      then:
        cpp-options: -DRELEASE
      else:
        dependencies:
        - gitrev >=1.2.0 && <1.4

tests:
  tests:
    main: Main.hs
    source-dirs: tests
    # ghc-options: -Wall
    dependencies:
      - hamler
      - hspec
      - hspec-discover
      - HUnit
      - tasty
      - hamler
      - shelly
      - tasty-golden
      - tasty-hspec
      - tasty-quickcheck
    default-extensions:
      - NoImplicitPrelude
      - LambdaCase
      - OverloadedStrings

flags:
  release:
    description: >
        Mark this build as a release build: prevents inclusion of extra
        info e.g. commit SHA in --version output)
    manual: false
    default: false

stability: experimental
