name: hamler
version: '0.2'
synopsis: The Hamler Programming Language
description: Hamler is a functional programming language inspired by Haskell and Standard ML,
  that compiles to CoreErlang.
category: Language, Compiler
author: Feng Lee <feng@emqx.io>
maintainer: Feng Lee <feng@emqx.io>, Yang M <yangm@emqx.io>
copyright: (c) 2013-17 Phil Freeman, (c) 2014-19 Gary Burgess, (c) 2020 Feng Lee, (c) other contributors (see CONTRIBUTORS.md)
license: BSD3
github: hamler-lang/hamler
homepage: https://hamler-lang.org/
extra-source-files:
  - README.md
  - stack.yaml
dependencies:
  - aeson >=1.0 && <1.5
  - aeson-better-errors >=0.8
  - aeson-pretty
  - ansi-terminal >=0.7.1 && <0.9
  - base >=4.11 && <4.13
  - base-compat >=0.6.0
  - boxes >=0.1.4 && <0.2.0
  - bytestring
  - Cabal >= 2.2 && <3.0
  - containers
  - CoreErlang
  - directory >=1.2.3
  - filepath
  - Glob >=0.9 && <0.10
  - language-javascript
  - shelly
  - lens
  - template-haskell
  - lifted-async >=0.10.0.3 && <0.10.1
  - lifted-base >=0.2.3 && <0.2.4
  - monad-control >=1.0.0.0 && <1.1
  - mtl >=2.1.0 && <2.3.0
  - parsec >=3.1.10
  - pattern-arrows >=0.0.2 && <0.1
  - pretty >= 1.1
  - pretty-simple
  - process >=1.2.0 && <1.7
  - protolude >=0.1.6 && <0.2.4
  - purescript
  - safe >=0.3.9 && <0.4
  - semigroups >=0.16.2 && <0.19
  - semialign >=1 && <1.1
  - sourcemap >=0.1.6
  - text
  - time
  - file-embed
  - transformers >=0.3.0 && <0.6
  - transformers-base >=0.4.0 && <0.5
  - transformers-compat >=0.3.0
  - utf8-string >=1 && <2
  - haskeline >= 0.7.5.0
build-tools:
  - happy ==1.19.9

library:
  source-dirs: src
  ghc-options: -Wall -O2
  # other-modules:
  default-extensions:
    - ConstraintKinds
    - DataKinds
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - DeriveGeneric
    - DerivingStrategies
    - EmptyDataDecls
    - FlexibleContexts
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - PatternGuards
    - PatternSynonyms
    - RankNTypes
    - RecordWildCards
    - OverloadedStrings
    - ScopedTypeVariables
    - TupleSections
    - ViewPatterns

executables:
  hamler:
    main: Main.hs
    source-dirs: app
    ghc-options: -Wall -O2
    dependencies:
      - ansi-wl-pprint
      - hamler
      - optparse-applicative >=0.13.0
    when:
    - condition: flag(release)
      then:
        cpp-options: -DRELEASE
      else:
        dependencies:
        - gitrev >=1.2.0 && <1.4

tests:
  tests:
    main: Main.hs
    source-dirs: tests
    ghc-options: -Wall
    dependencies:
      - aeson
      - ansi-terminal
      - hamler
      - hspec
      - hspec-discover
      - HUnit
      - optparse-applicative
      - shelly
      - sourcemap
      - tasty
      - tasty-golden
      - tasty-hspec
      - tasty-quickcheck
    default-extensions:
      - NoImplicitPrelude
      - LambdaCase
      - OverloadedStrings

flags:
  release:
    description: >
        Mark this build as a release build: prevents inclusion of extra
        info e.g. commit SHA in --version output)
    manual: false
    default: false

stability: experimental
