resolver: lts-13.26
pvp-bounds: upper
packages:
- '.'

extra-deps:
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1
- git: git@github.com:hamler-lang/CoreErlang.git
  commit: cd84d64d005c218f8f32682700dd062ab11c868c
- git: git@github.com:hamler-lang/purescript.git
  commit: fc4f7418874d2783f5fcebb14e14724dea76d24c
flags:
  these:
    assoc: false
    quickcheck: false
