resolver: lts-13.26
pvp-bounds: upper
packages:
- '.'

extra-deps:
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1
- git: git@github.com:hamler-lang/CoreErlang.git
  commit: a12462c3170130d4e808bb912e3938166ccda204
- git: git@github.com:hamler-lang/purescript.git
  commit: 5a070ef3117ac087b010632cf9243f581d523297
flags:
  these:
    assoc: false
    quickcheck: false
