resolver: lts-13.26
pvp-bounds: upper
packages:
- '.'

extra-deps:
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1
- git: git@github.com:hamler-lang/CoreErlang.git
  commit: afb0b731ff457d278403ab4bc134d3c88e09ea1f
- git: git@github.com:hamler-lang/purescript.git
  commit: 2c43709229b12e72dfc550ccf3efce6bfa60da72
flags:
  these:
    assoc: false
    quickcheck: false
