allow-different-user: true
resolver: lts-13.26
pvp-bounds: upper
packages:
- '.'

extra-deps:
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1
- github: hamler-lang/CoreErlang
  commit: 06639c2f00f93ce3ba62e4cb788abb9f7be117be
- github: hamler-lang/purescript
  commit: 6d8d13471140a141c7e904709f427fe6a5f8b59d
flags:
  these:
    assoc: false
    quickcheck: false
