allow-different-user: true
resolver: lts-13.26
pvp-bounds: upper
packages:
- '.'

extra-deps:
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1
- github: hamler-lang/CoreErlang
  commit: 2bacba611fed9eb773939964aa70e3ad49b8c816
- github: hamler-lang/purescript
  commit: 6e15bd836398c3aa94b1a2dae68773e095c635c3
- megaparsec-8.0.0@sha256:362f85e243ecbcb550e1de6e5c74ba5a50c09edaa1208c99bc5b9fd242227fc6,3808
flags:
  these:
    assoc: false
    quickcheck: false
